### ISSUE TITLE
Get audio file endpoint response doesn't conform to API spec

### ISSUE THREAD

**Issue by aapeliv** [persephone-tools/persephone-web-API#109] opened 2018-10-22 03:18 UTC
It returns this format (TS):

```ts
{
    id: number;
    filename: string;
    in_utterances: number[];
    url: string;
}
```

API spec currently claims it should be:

```ts
{
    id?: number;
    name: string;
    fileURL: string;
}
```

**Comment by shuttle1987** [comment] 2018-10-22 05:10
This is a duplicate of #106

**Closed** 2018-10-28 13:36 UTC
Labels: duplicate
