### ISSUE TITLE
POST /corpus creates partitions incorrectly

### ISSUE THREAD

**Issue by aapeliv** [persephone-tools/persephone-web-API#161] opened 2018-11-20 00:55 UTC
In:

```
{
    "featureType": "fbank",
    "labelType": "phonemes",
    "name": "test",
    "testing": [
        3
    ],
    "training": [
        1
    ],
    "validation": [
        2
    ]
}
```

Out:

```
{
    "featureType": "fbank",
    "filesystem_path": "aae94e68-ec5e-11e8-9b90-acde48001122",
    "id": 1,
    "labelType": "phonemes",
    "max_samples": 60,
    "name": "test",
    "partition": {
        "testing": [
            1
        ],
        "training": [
            1
        ],
        "validation": [
            1
        ]
    },
    "preprocessed": false
}
```

**Comment by shuttle1987** [comment] 2018-11-20 01:00
Not sure if this is a duplicate of #58 ?

**Comment by shuttle1987** [comment] 2018-11-20 01:02
It looks like there's 2 separate issues

* The partition is returning the keys for the partition objects directly and not the utterances
* Only keys are returned instead of deserialized objects

If you need to get the objects I think that likely warrants a new issue being opened. What do you think @aapeliv about this?

**Comment by aapeliv** [comment] 2018-11-20 01:07
It'd be good if the return type was `corpusInformation`, or a subset of it. I don't actually use that though. I just redo a `GET` request. The way the API spec is written should probably be refactored as well.

**Closed** 2018-11-23 06:46 UTC
Labels: bug
